-- Seed data for Saraya Al-Andalus (based on real catalog categories/images)

-- Default admin (password: Saraya@2026 - hashed with PBKDF2, placeholder replaced at setup)
-- NOTE: hash is generated by /api/auth/setup on first run if no users exist.

-- Settings (real company data only)
INSERT OR REPLACE INTO settings (key, value) VALUES
  ('company_name_ar', 'سرايا الأندلس للأثاث الفندقي والضيافة'),
  ('company_name_en', 'Saraya Al-Andalus Hospitality Furniture'),
  ('phone', '10 41617881'),
  ('whatsapp', '01227932213'),
  ('address_ar', 'ش عبدالله بن طلحه من جمال عبد الناصر، شرق المدينة'),
  ('address_en', 'Abdullah Ibn Talha St., off Gamal Abdel Nasser, East of the City'),
  ('whatsapp_default_msg_ar', 'مرحباً، أرغب في الاستفسار عن منتجات وخدمات سرايا الأندلس للأثاث الفندقي والضيافة.'),
  ('whatsapp_product_msg_ar', 'مرحباً، أرغب في الاستفسار عن منتج: {product}'),
  ('seo_title_ar', 'سرايا الأندلس للأثاث الفندقي والضيافة'),
  ('seo_description_ar', 'حلول أثاث وتجهيز متكاملة للمشروعات الفندقية والضيافة — جودة، تصميم، وتنفيذ حسب احتياجات المشروع.'),
  ('footer_about_ar', 'سرايا الأندلس توفر حلول أثاث وتجهيز متكاملة للمشروعات الفندقية والضيافة، مع التركيز على الجودة والتصميم والتنفيذ حسب احتياجات المشروع.'),
  ('footer_about_en', 'Saraya Al-Andalus provides integrated furniture and fit-out solutions for hospitality projects, focusing on quality, design, and project-tailored execution.');

-- Categories (from the real catalog structure)
INSERT OR IGNORE INTO categories (slug, name_ar, name_en, description_ar, image, sort_order, active) VALUES
  ('bedrooms', 'غرف النوم والأجنحة الفندقية', 'Bedrooms & Hotel Suites', 'غرف نوم وأجنحة فندقية بتصاميم عصرية وكلاسيكية تناسب الفنادق والشقق الفندقية.', '/static/images/bedroom-1.jpg', 1, 1),
  ('living-lobby', 'أثاث اللوبي والمعيشة', 'Living & Lobby Furniture', 'أطقم معيشة ولوبي فاخرة تناسب استقبالات الفنادق والمنتجعات.', '/static/images/living-lux.jpg', 2, 1),
  ('dining', 'غرف الطعام والمطاعم', 'Dining & Restaurants', 'طاولات وكراسي وبوفيهات لغرف الطعام والمطاعم والكافيهات.', '/static/images/dining-1.jpg', 3, 1),
  ('office', 'أثاث المكاتب ومساحات العمل', 'Office & Workspace', 'حلول أثاث مكتبي لمساحات العمل الإدارية في الفنادق والمنشآت.', '/static/images/office-1.jpg', 4, 1),
  ('storage', 'حلول التخزين', 'Storage Solutions', 'وحدات تخزين ذكية ودواليب وخزائن بتصاميم عملية.', '/static/images/storage-1.jpg', 5, 1),
  ('outdoor', 'الأثاث الخارجي', 'Outdoor Furniture', 'أثاث خارجي للحدائق والتراسات والمسابح في الفنادق والمنتجعات.', '/static/images/outdoor-1.jpg', 6, 1);

-- Products (real images from catalog, descriptions describe what's shown - no invented prices)
INSERT OR IGNORE INTO products (slug, name_ar, name_en, short_desc_ar, description_ar, category_id, main_image, featured, is_new, status, sort_order) VALUES
  ('hotel-bedroom-classic-gold', 'غرفة نوم فندقية كلاسيك', 'Classic Hotel Bedroom Set', 'غرفة نوم كاملة بتشطيب فاخر تناسب الأجنحة الفندقية.', 'غرفة نوم فندقية متكاملة تشمل السرير والدولاب والتسريحة والكمودينو، بتصميم كلاسيكي فاخر وخامات عالية الجودة مناسبة للفنادق والأجنحة.', 1, '/static/images/bedroom-1.jpg', 1, 0, 'published', 1),
  ('hotel-bedroom-modern-wood', 'غرفة نوم فندقية خشبية مودرن', 'Modern Wooden Hotel Bedroom', 'غرفة نوم بخامات خشبية دافئة وتصميم عصري.', 'غرفة نوم بتصميم عصري وخامات خشبية طبيعية، مثالية للشقق الفندقية والمنتجعات التي تبحث عن طابع دافئ وأنيق.', 1, '/static/images/bedroom-2.jpg', 1, 0, 'published', 2),
  ('hotel-bedroom-suite', 'جناح نوم فندقي', 'Hotel Bedroom Suite', 'جناح نوم متكامل بإضاءة وتفاصيل فندقية.', 'جناح نوم فندقي بتصميم متكامل يشمل وحدات الإضاءة والتخزين، مصمم لتجربة إقامة مريحة وفاخرة.', 1, '/static/images/bedroom-3.jpg', 0, 1, 'published', 3),
  ('twin-room-set', 'غرفة توين للفنادق', 'Twin Hotel Room Set', 'سريران منفصلان بتصميم عملي للغرف الفندقية.', 'غرفة توين بسريرين منفصلين وتشطيبات عملية سهلة الصيانة، مناسبة للفنادق والشقق الفندقية.', 1, '/static/images/bedroom-twin.jpg', 0, 0, 'published', 4),
  ('kids-bunk-room', 'غرفة أطفال بسرير بطابقين', 'Kids Bunk Bed Room', 'حلول غرف أطفال عملية للمنتجعات والشقق العائلية.', 'غرفة أطفال بسرير بطابقين مع وحدات تخزين مدمجة، تصميم آمن وعملي يناسب الوحدات العائلية في المنتجعات.', 1, '/static/images/kids-bunk-1.jpg', 0, 0, 'published', 5),
  ('classic-wardrobe-white', 'دولاب كلاسيك أبيض', 'Classic White Wardrobe', 'دولاب بتصميم كلاسيكي وتفاصيل راقية.', 'دولاب كلاسيكي بأبواب مزخرفة وتشطيب أبيض فاخر، يضيف لمسة أناقة للغرف الفندقية.', 5, '/static/images/wardrobe-classic.jpg', 0, 0, 'published', 6),
  ('dressing-unit', 'وحدة تسريحة بمرآة', 'Dressing Unit with Mirror', 'تسريحة عملية بمرآة ووحدات أدراج.', 'وحدة تسريحة بمرآة كاملة وأدراج تخزين، تصميم عملي يناسب الغرف الفندقية والشقق.', 1, '/static/images/dressing-1.jpg', 0, 0, 'published', 7),
  ('lobby-sofa-modern', 'أطقم جلوس مودرن للوبي', 'Modern Lobby Seating', 'أطقم كنب عصرية لمناطق الاستقبال.', 'أطقم جلوس عصرية بخطوط نظيفة وخامات مريحة، مصممة لمناطق الاستقبال واللوبي في الفنادق.', 2, '/static/images/living-1.jpg', 1, 0, 'published', 8),
  ('living-set-luxury', 'طقم معيشة فاخر', 'Luxury Living Set', 'طقم معيشة فاخر بتفاصيل كلاسيكية.', 'طقم معيشة فاخر بتنجيد راقٍ وتفاصيل كلاسيكية، يناسب الأجنحة الرئاسية ومناطق الضيافة المميزة.', 2, '/static/images/living-lux.jpg', 1, 0, 'published', 9),
  ('royal-majlis-set', 'طقم مجلس ملكي', 'Royal Majlis Set', 'مجلس فاخر بطراز ملكي للمساحات المميزة.', 'طقم مجلس بطراز ملكي فاخر وتنجيد مميز، مثالي لقاعات كبار الزوار ومناطق الضيافة الفاخرة.', 2, '/static/images/living-royal.jpg', 0, 0, 'published', 10),
  ('classic-salon', 'صالون كلاسيك', 'Classic Salon', 'صالون كلاسيكي أنيق لمناطق الاستقبال.', 'صالون كلاسيكي بتفاصيل أنيقة، يناسب الاستقبالات والمساحات شبه الرسمية في المنشآت الفندقية.', 2, '/static/images/living-classic.jpg', 0, 0, 'published', 11),
  ('dining-set-modern', 'طقم سفرة مودرن', 'Modern Dining Set', 'طاولة طعام وكراسي بتصميم عصري.', 'طقم سفرة عصري بخامات عالية الجودة، مناسب لمطاعم الفنادق وغرف الطعام الخاصة.', 3, '/static/images/dining-1.jpg', 1, 0, 'published', 12),
  ('dining-set-premium', 'سفرة فاخرة', 'Premium Dining Set', 'سفرة فاخرة لغرف طعام مميزة.', 'طقم سفرة فاخر بتشطيبات مميزة، يناسب المطاعم الراقية وقاعات الطعام في الفنادق.', 3, '/static/images/dining-2.jpg', 0, 1, 'published', 13),
  ('buffet-classic', 'بوفيه كلاسيك', 'Classic Buffet', 'بوفيه كلاسيكي بتفاصيل خشبية راقية.', 'بوفيه كلاسيكي بمرآة وتفاصيل خشبية مشغولة، قطعة مميزة لغرف الطعام الفاخرة.', 3, '/static/images/buffet-classic.jpg', 0, 0, 'published', 14),
  ('crockery-unit', 'وحدة عرض أطباق', 'Crockery Display Unit', 'وحدة عرض بإضاءة مدمجة للأطباق والتحف.', 'وحدة عرض أنيقة بإضاءة مدمجة لعرض الأطباق والتحف في المطاعم وغرف الطعام.', 3, '/static/images/crockery.jpg', 0, 0, 'published', 15),
  ('office-desk-executive', 'مكتب إداري', 'Executive Office Desk', 'مكتب إداري بتصميم عملي وأنيق.', 'مكتب إداري بخامات خشبية عالية الجودة وتصميم عملي، يناسب المكاتب الإدارية في الفنادق والشركات.', 4, '/static/images/office-1.jpg', 0, 0, 'published', 16),
  ('workspace-solutions', 'حلول مساحات العمل', 'Workspace Solutions', 'تجهيز متكامل لمساحات العمل المشتركة.', 'حلول متكاملة لتجهيز مساحات العمل المشتركة والمكاتب الإدارية بأثاث عملي ومريح.', 4, '/static/images/office-3.jpg', 0, 0, 'published', 17),
  ('smart-storage-table', 'طاولة تخزين ذكية', 'Smart Storage Table', 'طاولة متعددة الاستخدامات بتخزين مدمج.', 'طاولة ذكية قابلة للرفع مع مساحات تخزين مدمجة، حل عملي للمساحات المحدودة في الشقق الفندقية.', 5, '/static/images/storage-smart.jpg', 0, 1, 'published', 18),
  ('storage-shelving', 'وحدات أرفف تخزين', 'Storage Shelving Units', 'أرفف تخزين خشبية بتصميم مرن.', 'وحدات أرفف خشبية بتكوينات مرنة، تناسب المكتبات ومناطق العرض والتخزين.', 5, '/static/images/storage-3.jpg', 0, 0, 'published', 19),
  ('outdoor-lounge', 'جلسة خارجية', 'Outdoor Lounge Set', 'جلسات خارجية مريحة للحدائق والتراسات.', 'جلسة خارجية بخامات مقاومة للعوامل الجوية، مثالية لحدائق الفنادق والتراسات ومناطق المسابح.', 6, '/static/images/outdoor-1.jpg', 1, 0, 'published', 20),
  ('outdoor-garden-set', 'طقم حديقة', 'Garden Furniture Set', 'أطقم حدائق متكاملة للمنتجعات.', 'طقم حديقة متكامل بتصميم مريح وخامات معالجة، يناسب المساحات الخارجية في المنتجعات والفنادق.', 6, '/static/images/outdoor-2.jpg', 0, 0, 'published', 21);

-- Product gallery images
INSERT OR IGNORE INTO product_images (product_id, url, sort_order) VALUES
  (1, '/static/images/bedroom-1.jpg', 1),
  (1, '/static/images/bedroom-4.jpg', 2),
  (2, '/static/images/bedroom-2.jpg', 1),
  (2, '/static/images/bedroom-hotel.jpg', 2),
  (5, '/static/images/kids-bunk-1.jpg', 1),
  (5, '/static/images/kids-bunk-2.jpg', 2),
  (8, '/static/images/living-1.jpg', 1),
  (8, '/static/images/living-2.jpg', 2),
  (8, '/static/images/living-3.jpg', 3),
  (12, '/static/images/dining-1.jpg', 1),
  (12, '/static/images/dining-3.jpg', 2),
  (16, '/static/images/office-1.jpg', 1),
  (16, '/static/images/office-2.jpg', 2),
  (20, '/static/images/outdoor-1.jpg', 1),
  (20, '/static/images/outdoor-3.jpg', 2);

-- Services (from catalog "what we offer": Custom Furniture Design, Interior Styling & Consultation, Delivery & Assembly, Space Planning Solutions, After-Sales Support, Furniture Warranty, Renovation & Makeover)
INSERT OR IGNORE INTO services (slug, title_ar, title_en, short_desc_ar, description_ar, icon, image, sort_order, active) VALUES
  ('custom-design', 'تصميم أثاث حسب الطلب', 'Custom Furniture Design', 'تصميم وتنفيذ أثاث مخصص حسب احتياجات مشروعك.', 'نصمم وننفذ أثاثاً مخصصاً يلبي متطلبات مشروعك الفندقي من حيث المقاسات والخامات والطراز، مع الالتزام بهوية المشروع.', 'fa-pencil-ruler', '/static/images/desk-unit.jpg', 1, 1),
  ('interior-consultation', 'استشارات التصميم الداخلي', 'Interior Styling & Consultation', 'استشارات متخصصة في تنسيق وتجهيز المساحات.', 'نقدم استشارات متخصصة في التصميم الداخلي وتنسيق المساحات الفندقية لتحقيق أفضل تجربة للنزلاء.', 'fa-comments', '/static/images/living-2.jpg', 2, 1),
  ('delivery-assembly', 'التوريد والتركيب', 'Delivery & Assembly', 'توصيل وتركيب احترافي في موقع المشروع.', 'فريق متخصص للتوصيل والتركيب في موقع المشروع مع الالتزام بالجداول الزمنية ومعايير الجودة.', 'fa-truck', '/static/images/storage-2.jpg', 3, 1),
  ('space-planning', 'حلول تخطيط المساحات', 'Space Planning Solutions', 'تخطيط ذكي للمساحات لتحقيق أقصى استفادة.', 'ندرس المساحات ونضع حلول توزيع الأثاث المثلى لتحقيق أقصى استفادة وظيفية وجمالية من كل متر.', 'fa-vector-square', '/static/images/office-4.jpg', 4, 1),
  ('after-sales', 'دعم ما بعد البيع', 'After-Sales Support', 'خدمة ودعم مستمر بعد التسليم.', 'نوفر دعماً مستمراً بعد التسليم يشمل الصيانة والمتابعة لضمان استمرارية الجودة.', 'fa-headset', '/static/images/living-3.jpg', 5, 1),
  ('renovation', 'التجديد وإعادة التأهيل', 'Renovation & Makeover', 'تجديد وتحديث المساحات الفندقية القائمة.', 'نقدم خدمات تجديد وإعادة تأهيل للمنشآت الفندقية القائمة لتحديث مظهرها ورفع كفاءتها التشغيلية.', 'fa-paint-roller', '/static/images/niche-1.jpg', 6, 1);

-- Why choose us
INSERT OR IGNORE INTO why_us_items (icon, title_ar, title_en, description_ar, sort_order, active) VALUES
  ('fa-gem', 'جودة الخامات', 'Quality Materials', 'نستخدم خامات عالية الجودة مختارة بعناية لتناسب الاستخدام الفندقي المكثف.', 1, 1),
  ('fa-drafting-compass', 'تصميم حسب المشروع', 'Project-Tailored Design', 'كل مشروع له احتياجاته — نصمم وننفذ حسب متطلبات مشروعك بالتحديد.', 2, 1),
  ('fa-handshake', 'شريك واحد متكامل', 'One Integrated Partner', 'من التصميم إلى التوريد والتركيب — حلول متكاملة من جهة واحدة.', 3, 1),
  ('fa-clock', 'التزام بالمواعيد', 'On-Time Delivery', 'نلتزم بالجداول الزمنية المتفق عليها لتشغيل مشروعك في موعده.', 4, 1);

-- Homepage sections
INSERT OR IGNORE INTO home_sections (section_key, title_ar, title_en, content_ar, content_en, image, cta_text_ar, cta_url, sort_order, active) VALUES
  ('hero', 'أثاث فندقي يليق بمشروعك', 'Hospitality Furniture Worthy of Your Project', 'سرايا الأندلس توفر حلول أثاث وتجهيز متكاملة للمشروعات الفندقية والضيافة — جودة، تصميم، وتنفيذ حسب احتياجات المشروع.', 'Saraya Al-Andalus provides integrated furniture and fit-out solutions for hospitality projects.', '/static/images/hero-living.jpg', 'استكشف منتجاتنا', '/products', 1, 1),
  ('about', 'من نحن', 'About Us', 'سرايا الأندلس للأثاث الفندقي والضيافة — نعمل في مجال تجهيز الفنادق والشقق الفندقية والمنتجعات بحلول أثاث متكاملة تجمع بين الجودة والتصميم والعملية، مع تنفيذ مخصص حسب احتياجات كل مشروع.', NULL, '/static/images/living-lux.jpg', 'اعرف المزيد', '/about', 2, 1),
  ('categories', 'حلولنا وفئات منتجاتنا', 'Our Solutions', NULL, NULL, NULL, NULL, NULL, 3, 1),
  ('featured', 'منتجات مميزة', 'Featured Products', NULL, NULL, NULL, NULL, NULL, 4, 1),
  ('services', 'خدماتنا', 'Our Services', NULL, NULL, NULL, NULL, NULL, 5, 1),
  ('projects', 'مشاريعنا', 'Our Projects', NULL, NULL, NULL, NULL, NULL, 6, 1),
  ('why_us', 'لماذا سرايا الأندلس؟', 'Why Choose Us', NULL, NULL, NULL, NULL, NULL, 7, 1),
  ('cta', 'ابدأ مشروعك معنا', 'Start Your Project With Us', 'تواصل معنا الآن للحصول على عرض سعر مخصص لمشروعك الفندقي.', NULL, NULL, 'اطلب عرض سعر', '/quote', 8, 1);
